apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot-cli-cronjob
spec:
  schedule: "0 45 9 * *" # Runs every day at 9:45 AM CET
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: snapshot-cli
              image: ghcr.io/kengou/snapshot-cli:5ceee73
              imagePullPolicy: IfNotPresent
              command: ["/snapshot-cli", "--snapshot", "create"]
              env:
                - name: OS_AUTH_URL
                  value: ""
                - name: OS_AUTH_VERSION
                  value: ""
                - name: OS_PASSWORD
                  value: ""
                - name: OS_PROJECT_DOMAIN_NAME
                  value: ""
                - name: OS_PROJECT_NAME
                  value: ""
                - name: OS_USER_DOMAIN_NAME
                  value: ""
          restartPolicy: OnFailure